# -*- coding: utf-8 -*-
"""DataEngTest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTCSTpeSMIEdMbqZzfV5YN1Gea_s_MDj
"""

!pip install faker tqdm

!python data_generator.py

#